### ISSUE TITLE
Call to a member function getValue() on null | Admidio 4.1.9

### ISSUE THREAD

**Issue by GaneshKandu** [Admidio/admidio#1249]
**Describe the bug**
```
[type] => 1 [message] => Uncaught Error: Call to a member function getValue() on null in adm_program/system/classes/User.php:1438
Stack trace: 
#0 adm_program/system/classes/User.php(1795): User->invalidateAllOtherLogins() 
#1 adm_program/installation/install_steps/start_installation.php(218): User->setPassword('password') 
#2 adm_program/installation/installation.php(170): require_once('/home/admin/publ...') 
#3 {main} thrown [file] => adm_program/system/classes/User.php [line] => 1438
```

**To Reproduce**
Steps to reproduce :
[https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:installation](https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:installation)  getting this error on step 9

**Expected behavior**
Similar to step 10 mansioned on link
[https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:installation](https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:installation)

**Screenshots**
getting blank screen

**Desktop (please complete the following information):**
 - OS: Centos Linux
 - Browser Firefox 95.0.2 (64-bit)
 - Version 4.1.0
 - PHP 7.2.34
 - MySQL 5.5.62

**Comment by Fasse** [comment]
Thanks for the issue report. We will release a new version soon.
