### ISSUE TITLE
Admidio DB setup is stuck with PostgreSQL

### ISSUE THREAD

**Issue by vmindru** [Admidio/admidio#1305]
**Describe the bug**

Can not deploy/install admidio using admidio/latest , deployment gets stuck during  adm_program/installation/installation.php?step=start_installation

**To Reproduce**
1.  Create ECS Fargate service/container 
2.  Fill in DB details  - using PSQL option
3.  Fill in Setup details 
4.  Setup hangs on creating DB's , NEW HTTP requests are rejected with 500 error 
5.  Observe in logs 

```[Tue Sep 13 09:04:26.515839 2022] [php7:error] [pid 129] [client 89.0.0.1:51655] PHP Fatal error:  Uncaught UnexpectedValueException: Settings name "system_language" does not exist! in /opt/app-root/src/adm_program/system/classes/SettingsManager.php:140\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/SettingsManager.php(215): SettingsManager->get('system_language', false)\n#1 /opt/app-root/src/adm_program/system/common.php(121): SettingsManager->getString('system_language')\n#2 /opt/app-root/src/index.php(23): require_once('/opt/app-root/s...')\n#3 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/SettingsManager.php on line 140```

**Expected behavior**

Deployment works 

**Desktop (please complete the following information):**
 - Browser: Chrome 
 

**Additional context**

**Comment by vmindru** [comment]
I have tested the same on a local host with simple docker

```[root@ip-172-31-32-254 ec2-user]# cat start_admidio
docker run --detach -it --name Admidio \
  --memory="1024m" --cpu-quota="80000" --cpuset-cpus="0-1" \
  -p 8080:8080 \
  --restart="unless-stopped" \
  -v /data/Admidio-files:/var/www/admidio/adm_my_files \
  -v /data/Admidio-themes:/var/www/admidio/adm_themes \
  -v /data/Admidio-plugins:/var/www/admidio/adm_plugins \
  admidio/admidio:latest
[root@ip-172-31-32-254 ec2-user]# docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                     PORTS                                                 NAMES
c74954ccd64f   admidio/admidio:latest   "container-entrypoin…"   2 minutes ago   Up 2 minutes (unhealthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 8443/tcp   Admidio
[root@ip-172-31-32-254 ec2-user]#
```

**Comment by vmindru** [comment]
stuck at

![image](https://user-images.githubusercontent.com/7345517/189888520-d043d676-5517-4dea-8aa7-c5fcb0051b3a.png)

**Comment by vmindru** [comment]
```[Tue Sep 13 11:23:11.401066 2022] [php7:error] [pid 193] [client 127.0.0.1:42098] PHP Fatal error:  Uncaught UnexpectedValueException: Settings name "system_language" does not exist! in /opt/app-root/src/adm_program/system/classes/SettingsManager.php:140\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/SettingsManager.php(215): SettingsManager->get('system_language', false)\n#1 /opt/app-root/src/adm_program/system/common.php(121): SettingsManager->getString('system_language')\n#2 /opt/app-root/src/adm_program/overview.php(18): require_once('/opt/app-root/s...')\n#3 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/SettingsManager.php on line 140
127.0.0.1 - - [13/Sep/2022:11:23:11 +0000] "GET /adm_program/overview.php HTTP/1.1" 500 - "-" "curl/7.61.1"
```

**Comment by vmindru** [comment]
access logs during setup 


```
89.0.0.14 - - [13/Sep/2022:12:19:26 +0000] "POST /adm_program/installation/installation.php?step=create_organization HTTP/1.1" 200 30016 "http://sks.aws.mindruv.eu:8080/adm_program/installation/installation.php?step=connect_database" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
127.0.0.1 - - [13/Sep/2022:12:19:42 +0000] "GET /adm_program/overview.php HTTP/1.1" 302 - "-" "curl/7.61.1"
89.0.0.14 - - [13/Sep/2022:12:19:59 +0000] "POST /adm_program/installation/installation.php?step=create_administrator HTTP/1.1" 200 7934 "http://sks.aws.mindruv.eu:8080/adm_program/installation/installation.php?step=create_organization" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
89.0.0.14 - - [13/Sep/2022:12:20:10 +0000] "POST /adm_program/installation/installation.php?step=create_config HTTP/1.1" 200 3798 "http://sks.aws.mindruv.eu:8080/adm_program/installation/installation.php?step=create_administrator" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"





89.0.0.14 - - [13/Sep/2022:12:21:02 +0000] "-" 408 - "-" "-"
[Tue Sep 13 12:21:14.491432 2022] [php7:error] [pid 193] [client 127.0.0.1:43766] PHP Fatal error:  Uncaught UnexpectedValueException: Settings name "system_language" does not exist! in /opt/app-root/src/adm_program/system/classes/SettingsManager.php:140\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/SettingsManager.php(215): SettingsManager->get('system_language', false)\n#1 /opt/app-root/src/adm_program/system/common.php(121): SettingsManager->getString('system_language')\n#2 /opt/app-root/src/adm_program/overview.php(18): require_once('/opt/app-root/s...')\n#3 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/SettingsManager.php on line 140
127.0.0.1 - - [13/Sep/2022:12:21:14 +0000] "GET /adm_program/overview.php HTTP/1.1" 500 - "-" "curl/7.61.1"


```

**Comment by Fasse** [comment]
Hmm, that is strange. I tried a new installation with pgsql on my local machine and all works fine. Maybe something with the docker environment, but there I have no knowledge :-(

It looks like the installation process does nothing. Because the error later doesn'T find an entry in the database that should be there.

**Comment by Fasse** [comment]
Thanks for the detailed bug report. I could reproduce that error on my local machine. Something is wrong with the installation and PostgreSQL.
