### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool

### ISSUE THREAD

**Issue by WalterWampe** [Admidio/admidio#1325]
Error thrown starting up using docker-compose on Ubuntu 22.04.1 LTS.

--- 

## docker-compose.yaml:
```
version: "3.9"


# https://github.com/Admidio/admidio/blob/master/README-Docker.md

services:
  db:
    restart: unless-stopped
    image: mariadb:10.4.13
    container_name: admidio-mariaDB
    volumes:
      - "/opt/volumes/admidio/mariadb/config:/etc/mysql/conf.d"
      - "/opt/volumes/admidio/mariadb/data:/var/lib/mysql"
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=admidio
      - MYSQL_USER=admidio
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=rootpasswd"]
      interval: 10s
      timeout: 10s
      retries: 5

  admidio:
    restart: unless-stopped
    image: admidio/admidio:latest
    container_name: admidio
    depends_on:
      # - db
      db:
        condition: service_healthy
    volumes:
      - /opt/volumes/admidio/files:/opt/app-root/src/adm_my_files
      - /opt/volumes/admidio/themes:/opt/app-root/src/adm_themes
      - /opt/volumes/admidio/plugins:/opt/app-root/src/adm_plugins
    ports:
      - 1142:8080
    environment:
      - ADMIDIO_DB_TYPE=mysql
      - ADMIDIO_DB_HOST=db:3306
      - ADMIDIO_DB_NAME=admidio
      - ADMIDIO_DB_USER=admidio
      - ADMIDIO_DB_PASSWORD=password
      - ADMIDIO_DB_TABLE_PRAEFIX=gbv
      # - ADMIDIO_MAIL_RELAYHOST=hostname.domain.at:25
      - ADMIDIO_LOGIN_FOR_UPDATE=1
      - ADMIDIO_ORGANISATION=GBV
      - ADMIDIO_PASSWORD_HASH_ALGORITHM=DEFAULT
      - TZ=Europe/Berlin
      #- HTTPD_START_SERVERS=8
      #- DOCUMENTROOT=/
      #- PHP_MEMORY_LIMIT=256M
      #- ERROR_REPORTING=E_ALL & ~E_NOTICE
      #- DISPLAY_ERRORS=ON
      #- DISPLAY_STARTUP_ERRORS=OFF
      #- TRACK_ERRORS=OFF
      #- HTML_ERRORS=ON
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "com.centurylinklabs.watchtower.enable=true"

``` 
---
## admidio log:
```
[INFO ] provisioning missing directory adm_plugins


[INFO ] provisioning missing directory adm_themes


[INFO ] provisioning missing directory adm_my_files


[INFO ] set filesystem permissions (chown -R default:root .)


[INFO ] configure ServerName in /etc/httpd/conf/httpd.conf


[INFO ] configure postfix set inet_protocols to ipv4 since ipv6 is disabled (net.ipv6.conf.all.disable_ipv6=1)


[INFO ] execute postfix start


[INFO ] execute postfix status


[INFO ] execute mailq


Mail queue is empty


[INFO ] generate admidio config.php file


[INFO ] configure admidio config.php file


[INFO ] run apache with php enabled (/usr/libexec/s2i/run)


=> sourcing 20-copy-config.sh ...


---> 13:09:41     Processing additional arbitrary httpd configuration provided by s2i ...


=> sourcing 00-documentroot.conf ...


=> sourcing 50-mpm-tuning.conf ...


=> sourcing 40-ssl-certs.sh ...


[Sat Nov 12 13:09:41.180890 2022] [suexec:notice] [pid 128] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)


[Sat Nov 12 13:09:41.182587 2022] [ssl:warn] [pid 128] AH01909: 3548ff04998e:8443:0 server certificate does NOT include an ID which matches the server name


[Sat Nov 12 13:09:41.288993 2022] [ssl:warn] [pid 128] AH01909: 3548ff04998e:8443:0 server certificate does NOT include an ID which matches the server name


[Sat Nov 12 13:09:41.289194 2022] [lbmethod_heartbeat:notice] [pid 128] AH02282: No slotmem from mod_heartmonitor


[Sat Nov 12 13:09:41.289274 2022] [http2:warn] [pid 128] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.


[Sat Nov 12 13:09:41.435275 2022] [mpm_prefork:notice] [pid 128] AH00163: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k configured -- resuming normal operations


[Sat Nov 12 13:09:41.435529 2022] [core:notice] [pid 128] AH00094: Command line: 'httpd -D FOREGROUND'


[Sat Nov 12 13:10:09.113248 2022] [php7:error] [pid 153] [client 127.0.0.1:40876] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /opt/app-root/src/adm_program/system/classes/Database.php:460\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/Database.php(389): Database->loadTableColumnsProperties('gbv_sessions')\n#1 /opt/app-root/src/adm_program/system/classes/TableAccess.php(622): Database->getTableColumnsProperties('gbv_sessions')\n#2 /opt/app-root/src/adm_program/system/classes/TableAccess.php(140): TableAccess->setColumnsInfos()\n#3 /opt/app-root/src/adm_program/system/classes/TableAccess.php(104): TableAccess->clear()\n#4 /opt/app-root/src/adm_program/system/classes/Session.php(60): TableAccess->__construct(Object(Database), 'gbv_sessions', 'ses')\n#5 /opt/app-root/src/adm_program/system/common.php(88): Session->__construct(Object(Database), 'ADMIDIO_GBV_JSD...')\n#6 /opt/app-root/src/adm_program/overview.php(18): require_once('/opt/app-root/s...')\n#7 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/Database.php on line 460


127.0.0.1 - - [12/Nov/2022:13:10:09 +0100] "GET /adm_program/overview.php HTTP/1.1" 500 - "-" "curl/7.61.1"


[Sat Nov 12 13:10:39.212055 2022] [php7:error] [pid 152] [client 127.0.0.1:38662] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /opt/app-root/src/adm_program/system/classes/Database.php:460\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/Database.php(389): Database->loadTableColumnsProperties('gbv_sessions')\n#1 /opt/app-root/src/adm_program/system/classes/TableAccess.php(622): Database->getTableColumnsProperties('gbv_sessions')\n#2 /opt/app-root/src/adm_program/system/classes/TableAccess.php(140): TableAccess->setColumnsInfos()\n#3 /opt/app-root/src/adm_program/system/classes/TableAccess.php(104): TableAccess->clear()\n#4 /opt/app-root/src/adm_program/system/classes/Session.php(60): TableAccess->__construct(Object(Database), 'gbv_sessions', 'ses')\n#5 /opt/app-root/src/adm_program/system/common.php(88): Session->__construct(Object(Database), 'ADMIDIO_GBV_JSD...')\n#6 /opt/app-root/src/adm_program/overview.php(18): require_once('/opt/app-root/s...')\n#7 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/Database.php on line 460


127.0.0.1 - - [12/Nov/2022:13:10:39 +0100] "GET /adm_program/overview.php HTTP/1.1" 500 - "-" "curl/7.61.1"
```

---

I don't know what to do, how can this be fixed?

Thank you for your work!
Grüße nach Wien.
Walter

**Comment by richardklose** [comment]
Same issue here. Was able to open https://<url>/adm_program/installation/installation.php in the browser, which opened the create_organization step. After this and the following step the page stayed blank and the log of the Admidio container again shows the same error:
```
[Fri Dec 23 10:29:44.340007 2022] [php7:error] [pid 140] [client 127.0.0.1:49342] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /opt/app-root/src/adm_program/system/classes/Database.php:460
Stack trace:
#0 /opt/app-root/src/adm_program/system/classes/Database.php(389): Database->loadTableColumnsProperties('adm_sessions')
#1 /opt/app-root/src/adm_program/system/classes/TableAccess.php(622): Database->getTableColumnsProperties('adm_sessions')
#2 /opt/app-root/src/adm_program/system/classes/TableAccess.php(140): TableAccess->setColumnsInfos()
#3 /opt/app-root/src/adm_program/system/classes/TableAccess.php(104): TableAccess->clear()
#4 /opt/app-root/src/adm_program/system/classes/Session.php(60): TableAccess->__construct(Object(Database), 'adm_sessions', 'ses')
#5 /opt/app-root/src/adm_program/system/common.php(88): Session->__construct(Object(Database), 'ADMIDIO_693117_...')
#6 /opt/app-root/src/adm_program/overview.php(18): require_once('/opt/app-root/s...')
#7 {main}
  thrown in /opt/app-root/src/adm_program/system/classes/Database.php on line 460
```

My docker-compose.yml:
```yaml
---
version: '3.9'

networks:
  admidio-693117:

services:
  db:
    restart: unless-stopped
    image: mariadb:10.5.8
    container_name: Admidio-MariaDB_693117
    networks:
      - admidio-693117
    volumes:
      - /srv/docker/693117/volumes/mariadb_conf.d:/etc/mysql/conf.d
      - /srv/docker/693117/volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: admidio
      MYSQL_USER: admidio
      MYSQL_PASSWORD: ***

  admidio:
    restart: unless-stopped
    image: admidio/admidio:v4.1.17
    container_name: Admidio_693117
    networks:
      - admidio-693117
    depends_on:
      - db
    volumes:
      - /srv/docker/693117/volumes/adm_my_files:/opt/app-root/src/adm_my_files
      - /srv/docker/693117/volumes/adm_themes:/opt/app-root/src/adm_themes
      - /srv/docker/693117/volumes/adm_plugins:/opt/app-root/src/adm_plugins
    ports:
      - 10.0.2.6:23117:8080
    environment:
      ADMIDIO_DB_TYPE: mysql
      ADMIDIO_DB_HOST: db:3306
      ADMIDIO_DB_NAME: admidio
      ADMIDIO_DB_USER: admidio
      ADMIDIO_DB_PASSWORD: ***
      ADMIDIO_ROOT_PATH: https://***
      ADMIDIO_ORGANISATION: "693117"
      TZ: "Europe/Berlin"
```

From the forum and other issues I read, that using a different browser could help. But it didn't in my case. I also tried older Container images (some 4.1.X, some 4.0.X) but this also didn't change anything.
I checked the MySQL container. Admidio has not created any tables in the admidio database there., it's empty.

**Comment by richardklose** [comment]
Did some more debugging and installed the mariadb-client into the Admidio container to test if the connection basically works. Looks good so far:
```
# (from inside the Admidio container)
bash-4.4# mysql -h db -u admidio -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1603
Server version: 10.5.8-MariaDB-1:10.5.8+maria~focal mariadb.org binary distribution
...
```

**Comment by richardklose** [comment]
After digging into the code and playing around, I found out it might be due to an existing config.php. I had one in my docker volumes because I recreated the container several times. After deleting it, I was able to finish installation by opening /adm_program/installation/installation.php manually in my browser and going through the installation steps.

**Comment by Fasse** [comment]
Ok, for my understanding of the problem:
1. you had already a config.php from tests before. Had this config.php the correct database credentials or invalid login data?
2. Now you oben /adm_program/installation/installation.php
3. You start at step create_organizations and got the documented error

**Comment by richardklose** [comment]
1. yes, correct credentials
2. yes, this immediately redirects to the create_organization step, I assume because database settings are already known from config.php. 
3. I am able to enter organization and admin details. The error appears after saving the admin details. As far as I understand the code, this might be at the point where everything is saved to the database.

**Comment by Fasse** [comment]
Hmm thats strange. I test this with my local installation (without docker) and it works :/

**Comment by schast** [comment]
Problem is that the automatic redirect is not working inside Docker Container.

adm_program/index.php
```
// if config file doesn't exists, than show installation dialog
if (!is_file(__DIR__ . '/../adm_my_files/config.php')) {
    header('Location: adm_program/installation/index.php');
    exit();
}
```

The config.php file is always dynamically created on Docker Container startup and always exists, also on new installations.

@Fasse:
We should also redirect to installation if config.php exists but no tables are in db?
Or we could add an new variable to config.php for new installations like "$gDbInitialized = 'false';". After sucessfully installation set to "$gDbInitialized = 'true';"

**Comment by WeT-Klb** [comment]
Hi, i am no programer - but can it be there´s a type mismatch in first line?
Shouldn´t it be "......exists, then....." instead of "than" ?

**Comment by schast** [comment]
Should work with current branch_v4.1.
Can you please test your installation with your docker-compose.yaml?

Required changes for your docker-compose.yaml:
```
  admidio:
    image: admidio/admidio:**branch_v4.1**
```

You should also set correct value for `ADMIDIO_ROOT_PATH` variable.
For example:     `- ADMIDIO_ROOT_PATH=http://localhost:1142`

**Comment by Fasse** [comment]
@schast is this issue now fixed?

**Comment by schast** [comment]
yes, my tests with the docker-compose.yml from above were successful.
