### ISSUE TITLE
Uncaught Error: Object of class MainMenu could not be converted to string

### ISSUE THREAD

**Issue by benhartwich** [Admidio/admidio#1364]
Hi,

I´ve upgraded to the latest version 4.2.2. from 4.1.13. After the upgrade I get the following error at nginx error log with php 7.4:

`2023/02/20 15:24:46 [error] 1352570#1352570: *1596359 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Object of class MainMenu could not be converted to string in /var/www/verwaltung/htdocs/admidio/adm_my_files/templates/compile/22f1c84a3e2a5cce88c41b1a186e3e1fada2862e_0.file.index.tpl.php:170
Stack trace:
#0 /var/www/verwaltung/htdocs/admidio/adm_program/libs/server/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63f3828f37a9c3_49718167()
#1 /var/www/verwaltung/htdocs/admidio/adm_program/libs/server/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /var/www/verwaltung/htdocs/admidio/adm_program/libs/server/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#3 /var/www/verwaltung/htdocs/admidio/adm_program/libs/server/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
`

How can I solve this problem?

**Comment by benhartwich** [comment]
Ups, sorry, missed to update adm_themes
