### ISSUE TITLE
Profile photo couldn't be saved

### ISSUE THREAD

**Issue by johnsonbrothers** [Admidio/admidio#1549]
**Describe the bug**

I try to upload my profile picture but my picture don´t show.

```
10.88.0.1 - - [16/Jan/2024:20:52:49 +0100] "POST //adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=b3449fdd-31f1-4fe7-8e35-ddb35c00420d HTTP/1.1" 200 3684 "https://servername.se/subpath/adm_program/modules/profile/profile_photo_edit.php?user_uuid=b3449fdd-31f1-4fe7-8e35-ddb35c00420d" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
[Tue Jan 16 20:52:49.632445 2024] [php:error] [pid 145] [client 10.88.0.1:47014] PHP Fatal error:  Uncaught TypeError: Image::setImageFromData(): Argument #1 ($imageData) must be of type string, resource given, called in /opt/app-root/src/adm_program/modules/profile/profile_photo_show.php on line 41 and defined in /opt/app-root/src/adm_program/system/classes/Image.php:361\nStack trace:\n#0 /opt/app-root/src/adm_program/modules/profile/profile_photo_show.php(41): Image->setImageFromData(Resource id #64)\n#1 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/Image.php on line 361, referer: https://servername.se/subpath/adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=b3449fdd-31f1-4fe7-8e35-ddb35c00420d
10.88.0.1 - - [16/Jan/2024:20:52:49 +0100] "GET //adm_program/modules/profile/profile_photo_show.php?user_uuid=b3449fdd-31f1-4fe7-8e35-ddb35c00420d&new_photo=1 HTTP/1.1" 500 321 "https://servername.se/subpath/adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=b3449fdd-31f1-4fe7-8e35-ddb35c00420d" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

**To Reproduce**
1. Go to 'My profile'
2. Click on 'upload profile picture'
3. choose your best profile picture
4. click on Upload profile picture
5. your best profile picture is not shown
6. See error in webserver-log

**Expected behavior**
My uploaded profile picture should be seen next to my name in my profile

**System (please complete the following information):**
 - Admidio-Version container Admidio 4.3
 - PHP n/a
 - Database PostgreSQL
 - Browser Firefox
 - Browser-Version 121.0

**Additional context**
I have admidio under a subpath on my nginx to use my regular LetsEncrypt certificate. everything else seems to work but not uploading profile pictures.

**Comment by Fasse** [comment]
@johnsonbrothers  Does this work with Admidio 4.2 and Postgres?

**Comment by johnsonbrothers** [comment]
I did not check that earlier. A quick test with version 4.2.14 just now. No, the photo did not save. 

```
10.0.2.100 - - [17/Jan/2024:21:53:41 +0100] "POST /adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=89cc637c-6f75-423e-b7f1-2c04f415571b HTTP/1.1" 200 3583 "http://localhost:8080/adm_program/modules/profile/profile_photo_edit.php?user_uuid=89cc637c-6f75-423e-b7f1-2c04f415571b" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
[Wed Jan 17 21:53:41.756873 2024] [php:error] [pid 153] [client 10.0.2.100:56024] PHP Fatal error:  Uncaught TypeError: imagecreatefromstring(): Argument #1 ($data) must be of type string, resource given in /opt/app-root/src/adm_program/system/classes/Image.php:362\nStack trace:\n#0 /opt/app-root/src/adm_program/system/classes/Image.php(362): imagecreatefromstring(Resource id #62)\n#1 /opt/app-root/src/adm_program/modules/profile/profile_photo_show.php(41): Image->setImageFromData(Resource id #62)\n#2 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/Image.php on line 362, referer: http://localhost:8080/adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=89cc637c-6f75-423e-b7f1-2c04f415571b
10.0.2.100 - - [17/Jan/2024:21:53:41 +0100] "GET /adm_program/modules/profile/profile_photo_show.php?user_uuid=89cc637c-6f75-423e-b7f1-2c04f415571b&new_photo=1 HTTP/1.1" 500 321 "http://localhost:8080/adm_program/modules/profile/profile_photo_edit.php?mode=upload&user_uuid=89cc637c-6f75-423e-b7f1-2c04f415571b" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

**Comment by Fasse** [comment]
Within the next version storing the profile photo in the database works also with postgres.
